### ISSUE TITLE
Unhandled internal server error

### ISSUE THREAD

**Issue by ftsell** [fsinfuhh/py_simple_openid_connect#12]
## The Error

When performing a login using this library, the following error happened during authentication.
It was not handled by the library in any way and not documented.

```
Internal Server Error: /auth/openid/login-callback/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/simple_openid_connect/integrations/django/views.py", line 64, in get
    token_response = client.authorization_code_flow.handle_authentication_result(
  File "/usr/local/lib/python3.9/dist-packages/simple_openid_connect/flows/authorization_code_flow/client.py", line 86, in handle_authentication_result
    return impl.handle_authentication_result(
  File "/usr/local/lib/python3.9/dist-packages/simple_openid_connect/flows/authorization_code_flow/__init__.py", line 70, in handle_authentication_result
    raise AuthenticationFailedError(
simple_openid_connect.exceptions.AuthenticationFailedError: error='access_denied' error_description=None error_uri=None state=None
```

## What we should do

We should handle this error better in the login-callback view to tell the user to try again or something similar.

**Comment by lilioid** [comment]
this should be fixed by now since the login-callback view now renders proper errors
