### ISSUE TITLE
`dict` object has no attribute `kty`

### ISSUE THREAD

**Issue by timonegk** [fsinfuhh/py_simple_openid_connect#2]
This error happens sometimes:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/django/views.py", line 85, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/simple_openid_connect/integrations/django/views.py", line 88, in get
    id_token = IdToken.parse_jws(token_response.id_token, client.provider_keys)
  File "/usr/local/lib/python3.9/dist-packages/simple_openid_connect/base_data.py", line 98, in parse_jws
    msg = verifier.verify_compact(value, signing_keys)
  File "/usr/local/lib/python3.9/dist-packages/cryptojwt/jws/jws.py", line 153, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)["msg"]
  File "/usr/local/lib/python3.9/dist-packages/cryptojwt/jws/jws.py", line 208, in verify_compact_verbose
    _keys = self.pick_keys(keys)
  File "/usr/local/lib/python3.9/dist-packages/cryptojwt/jwx.py", line 213, in pick_keys
    _keys = [k for k in keys if k.kty in _kty]
  File "/usr/local/lib/python3.9/dist-packages/cryptojwt/jwx.py", line 213, in <listcomp>
    _keys = [k for k in keys if k.kty in _kty]
AttributeError: 'dict' object has no attribute 'kty'
```

**Comment by Shevilll** [comment]
I guess it should be k.keys()
Dict objects don't have any attribute like kty!

**Comment by timonegk** [comment]
This is happening because `signing_keys` is a list of `dict` objects instead of `JWT` objects. So somewhere, the objects are not correctly deserialized.
